= natour Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog^], and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning^].

IMPORTANT: As per Semantic Versioning, the major version zero is for initial development and anything may change at any time.

== Unreleased

=== Added

- Add command line option to use short species names in the AsciiDoc output. The species names are truncated by removing the authority (botany only).

== 0.11.0 - 2023-04-15

=== Changed

- Specify files to load for a configuration instead of a file and directories.
- The configuration files must now be named `.natour.yml` (prefixed with a dot).

=== Fixed

- Do not abort creating reports if GPX files do not contain tracks.

== 0.10.0 - 2023-02-18

=== Fixed

- Prevent orphaned section titles and table captions in PDF output.

== 0.9.0 - 2022-10-08

=== Added

- Support colors for GPS tracks, waypoints and routes (`natour map create` command only).

=== Changed

- Omit empty columns of species lists in the AsciiDoc output.

=== Fixed

- Fix inconsistent handling of file errors in the command line interface.
- Fix the creation of map images.

== 0.8.0 - 2022-04-22

=== Added

- Add command to create map images from GPS tracks, waypoints and routes.
- Add command line option to display the version of this gem.

=== Changed

- Rename arguments of `Natour::MapGeoAdmin.save_image`, i.e. `tracks` to `gps_files`, `layers` to `map_layers` and `size` to `image_size`.
- Improve the error reporting on the command line interface in case of file errors.
- Rework the configuration; the structure and naming follows the command line interface and the keys are of type Ruby Symbol. For details, see the README file.
- Rework the command line interface. Use `natour --help` to get more information.
- Change `backend` and `draft_backend` arguments of `Natour::convert_report` to symbols.
- Rename `Natour::create` to `Natour::create_reports` and `Natour::convert` to `Natour::convert_report`.

=== Fixed

- Do not overwrite map images unless otherwise specified.
- Do not abort if the configuration file is empty.

== 0.7.0 - 2022-02-14

=== Added

- Add support for Ruby 3.0 and 3.1.
- Support species lists from https://www.birdlife.ch/de/content/eine-neue-moderne-vogel-app-fuer-die-schweiz[Vogelführer Birdlife Schweiz^].

=== Changed

- Return the filenames from `Natour::create` and `Natour::convert`.

=== Removed

- Drop support for Ruby 2.5.

=== Fixed

- Add revision date to the AsciiDoc output regardless of the author.
- Prevent conversion from being aborted if a built-in date/time attribute is missing.

== 0.6.0 - 2021-11-20

=== Fixed

- Support GPX files containing only mandatory elements (i.e. no extensions).
- Consider also the image dimensions to determine the orientation, even if the tag is present.

== 0.5.0 - 2021-08-16

=== Added

- Reflect the date of the last update in the revision date.
- Add captions to species lists in the AsciiDoc output.
- Group species lists by taxonomic groups in the AsciiDoc output.

=== Fixed

- Support species lists of https://www.flora-helvetica.ch/[Flora Helvetica^] exported from _Favoriten_.
- Consider botanical names with the authority name preceding the subspecies.

== 0.4.0 - 2021-05-02

=== Added

- Show date/time of images in draft output.
- Support preferred conversion backend for draft output.

=== Removed

- Remove redundant method `Natour::Image.portrait?`.

== 0.3.0 - 2021-03-07

=== Changed

- Sort the reports according to their GPS track.
- Bump minimum required Ruby version to 2.5.
- Change font in PDF output to support ♀ and ♂ symbols.

=== Fixed

- Make source code compatible with Ruby 2.5.

== 0.2.0 - 2021-01-24

=== Added

- Add this gem's name to the footer of the PDF output.
- Support species lists from https://www.ornitho.ch/[ornitho.ch^] (KML format only).
- Classify species lists by taxonomic groups (i.e. `Natour::SpeciesList.group`).

=== Changed

- Rename `Natour::SpeciesList.name` to `Natour::SpeciesList.title`.
- Return an empty array from `Natour::SpeciesList.load_file` if the format is unknown.
- Change the format of the start time in the AsciiDoc output from _12:30_ to _12:30 Uhr_.
- Change the format of the duration in the AsciiDoc output from _1h30_ to _1:30 h_.

=== Fixed

- Get the date from images even if the orientation tag is missing.
- Fix typo in help message.

== 0.1.0 - 2020-12-04

=== Added
- First release.
